components_manager:
    task_processors:
        main-task-processor:
            worker_threads: $worker-threads

        fs-task-processor:
            worker_threads: $worker-fs-threads

    default_task_processor: main-task-processor

    components:
        server:
            listener:
                port: $server-port
                task_processor: main-task-processor
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $logger-level
                    overflow_behavior: discard  # Drop logs if the system is too busy to write them down.

        # Dynamic config options. Cache is disabled, updates are disabled.
        dynamic-config:
            defaults:
                HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000

        http-client:
            load-enabled: $is_testing
            fs-task-processor: fs-task-processor

        dns-client:
            fs-task-processor: fs-task-processor

        testsuite-support: {}

        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        postgres-db:
            dbconnection: $dbconnection
            dbconnection#env: DB_CONNECTION
            blocking_task_processor: fs-task-processor
            dns_resolver: async
            sync-start: false
            connlimit_mode: manual

        auth-middleware: {}

        auth-middleware-pipeline-builder: {}

        background-task-manager: {}

        handler-login:
            path: /login
            method: GET,POST
            task_processor: main-task-processor

        handler-register:
            path: /register
            method: GET,POST
            task_processor: main-task-processor

        handler-user-info:
            path: /user/info
            method: GET,POST
            task_processor: main-task-processor
            middlewares:
                pipeline-builder: auth-middleware-pipeline-builder
                auth-middleware: {}

        handler-user-trade-submit:
            path: /user/trade/submit
            method: GET,POST
            task_processor: main-task-processor
            middlewares:
                pipeline-builder: auth-middleware-pipeline-builder
                auth-middleware: {}

        handler-user-trade-status:
            path: /user/trade/status
            method: GET,POST
            task_processor: main-task-processor
            middlewares:
                pipeline-builder: auth-middleware-pipeline-builder
                auth-middleware: {}

        handler-stock-price:
            path: /stock_price
            method: GET,POST
            task_processor: main-task-processor

        handler-trade-history:
            path: /trade_history
            method: GET,POST
            task_processor: main-task-processor
