version: "3"

services:
    db:
        image: postgres
        restart: always
        volumes:
            - ./data/db:/var/lib/postgresql/data
            - "./migrations/20241015203457_init.sql:/docker-entrypoint-initdb.d/init.sql"
        environment:
            - POSTGRES_DB=koshechko
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=DWCfSgJEmwhtUFNa4Grkx2

    nginx:
        image: nginx:alpine
        cpus: 1
        pids_limit: 1024
        mem_limit: 1G
        memswap_limit: 1G
        ulimits:
            nofile:
                soft: 12000
                hard: 12000
        restart: always
        stop_grace_period: 3s
        ports:
            - '3134:80'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./front:/var/www:ro
        depends_on:
            - app

    app:
        build: .
        restart: always
        depends_on:
            - db


    redis:
        image: redis
        restart: always
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
