/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: pr.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "pr.pb-c.h"
void   command__init
                     (Command         *message)
{
  static const Command init_value = COMMAND__INIT;
  *message = init_value;
}
size_t command__get_packed_size
                     (const Command *message)
{
  assert(message->base.descriptor == &command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t command__pack
                     (const Command *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t command__pack_to_buffer
                     (const Command *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Command *
       command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Command *)
     protobuf_c_message_unpack (&command__descriptor,
                                allocator, len, data);
}
void   command__free_unpacked
                     (Command *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   register_response__init
                     (RegisterResponse         *message)
{
  static const RegisterResponse init_value = REGISTER_RESPONSE__INIT;
  *message = init_value;
}
size_t register_response__get_packed_size
                     (const RegisterResponse *message)
{
  assert(message->base.descriptor == &register_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t register_response__pack
                     (const RegisterResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &register_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t register_response__pack_to_buffer
                     (const RegisterResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &register_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RegisterResponse *
       register_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RegisterResponse *)
     protobuf_c_message_unpack (&register_response__descriptor,
                                allocator, len, data);
}
void   register_response__free_unpacked
                     (RegisterResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &register_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   register_request__init
                     (RegisterRequest         *message)
{
  static const RegisterRequest init_value = REGISTER_REQUEST__INIT;
  *message = init_value;
}
size_t register_request__get_packed_size
                     (const RegisterRequest *message)
{
  assert(message->base.descriptor == &register_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t register_request__pack
                     (const RegisterRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &register_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t register_request__pack_to_buffer
                     (const RegisterRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &register_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RegisterRequest *
       register_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RegisterRequest *)
     protobuf_c_message_unpack (&register_request__descriptor,
                                allocator, len, data);
}
void   register_request__free_unpacked
                     (RegisterRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &register_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   login_challenge_msg1_request__init
                     (LoginChallengeMsg1Request         *message)
{
  static const LoginChallengeMsg1Request init_value = LOGIN_CHALLENGE_MSG1_REQUEST__INIT;
  *message = init_value;
}
size_t login_challenge_msg1_request__get_packed_size
                     (const LoginChallengeMsg1Request *message)
{
  assert(message->base.descriptor == &login_challenge_msg1_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t login_challenge_msg1_request__pack
                     (const LoginChallengeMsg1Request *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &login_challenge_msg1_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t login_challenge_msg1_request__pack_to_buffer
                     (const LoginChallengeMsg1Request *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &login_challenge_msg1_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LoginChallengeMsg1Request *
       login_challenge_msg1_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LoginChallengeMsg1Request *)
     protobuf_c_message_unpack (&login_challenge_msg1_request__descriptor,
                                allocator, len, data);
}
void   login_challenge_msg1_request__free_unpacked
                     (LoginChallengeMsg1Request *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &login_challenge_msg1_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   login_challenge_msg1_response__init
                     (LoginChallengeMsg1Response         *message)
{
  static const LoginChallengeMsg1Response init_value = LOGIN_CHALLENGE_MSG1_RESPONSE__INIT;
  *message = init_value;
}
size_t login_challenge_msg1_response__get_packed_size
                     (const LoginChallengeMsg1Response *message)
{
  assert(message->base.descriptor == &login_challenge_msg1_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t login_challenge_msg1_response__pack
                     (const LoginChallengeMsg1Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &login_challenge_msg1_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t login_challenge_msg1_response__pack_to_buffer
                     (const LoginChallengeMsg1Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &login_challenge_msg1_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LoginChallengeMsg1Response *
       login_challenge_msg1_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LoginChallengeMsg1Response *)
     protobuf_c_message_unpack (&login_challenge_msg1_response__descriptor,
                                allocator, len, data);
}
void   login_challenge_msg1_response__free_unpacked
                     (LoginChallengeMsg1Response *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &login_challenge_msg1_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   login_challenge_msg2_request__init
                     (LoginChallengeMsg2Request         *message)
{
  static const LoginChallengeMsg2Request init_value = LOGIN_CHALLENGE_MSG2_REQUEST__INIT;
  *message = init_value;
}
size_t login_challenge_msg2_request__get_packed_size
                     (const LoginChallengeMsg2Request *message)
{
  assert(message->base.descriptor == &login_challenge_msg2_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t login_challenge_msg2_request__pack
                     (const LoginChallengeMsg2Request *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &login_challenge_msg2_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t login_challenge_msg2_request__pack_to_buffer
                     (const LoginChallengeMsg2Request *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &login_challenge_msg2_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LoginChallengeMsg2Request *
       login_challenge_msg2_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LoginChallengeMsg2Request *)
     protobuf_c_message_unpack (&login_challenge_msg2_request__descriptor,
                                allocator, len, data);
}
void   login_challenge_msg2_request__free_unpacked
                     (LoginChallengeMsg2Request *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &login_challenge_msg2_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   login_challenge_msg2_response__init
                     (LoginChallengeMsg2Response         *message)
{
  static const LoginChallengeMsg2Response init_value = LOGIN_CHALLENGE_MSG2_RESPONSE__INIT;
  *message = init_value;
}
size_t login_challenge_msg2_response__get_packed_size
                     (const LoginChallengeMsg2Response *message)
{
  assert(message->base.descriptor == &login_challenge_msg2_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t login_challenge_msg2_response__pack
                     (const LoginChallengeMsg2Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &login_challenge_msg2_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t login_challenge_msg2_response__pack_to_buffer
                     (const LoginChallengeMsg2Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &login_challenge_msg2_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LoginChallengeMsg2Response *
       login_challenge_msg2_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LoginChallengeMsg2Response *)
     protobuf_c_message_unpack (&login_challenge_msg2_response__descriptor,
                                allocator, len, data);
}
void   login_challenge_msg2_response__free_unpacked
                     (LoginChallengeMsg2Response *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &login_challenge_msg2_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   list_comments_request__init
                     (ListCommentsRequest         *message)
{
  static const ListCommentsRequest init_value = LIST_COMMENTS_REQUEST__INIT;
  *message = init_value;
}
size_t list_comments_request__get_packed_size
                     (const ListCommentsRequest *message)
{
  assert(message->base.descriptor == &list_comments_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t list_comments_request__pack
                     (const ListCommentsRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &list_comments_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t list_comments_request__pack_to_buffer
                     (const ListCommentsRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &list_comments_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ListCommentsRequest *
       list_comments_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ListCommentsRequest *)
     protobuf_c_message_unpack (&list_comments_request__descriptor,
                                allocator, len, data);
}
void   list_comments_request__free_unpacked
                     (ListCommentsRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &list_comments_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   comment__init
                     (Comment         *message)
{
  static const Comment init_value = COMMENT__INIT;
  *message = init_value;
}
size_t comment__get_packed_size
                     (const Comment *message)
{
  assert(message->base.descriptor == &comment__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t comment__pack
                     (const Comment *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &comment__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t comment__pack_to_buffer
                     (const Comment *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &comment__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Comment *
       comment__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Comment *)
     protobuf_c_message_unpack (&comment__descriptor,
                                allocator, len, data);
}
void   comment__free_unpacked
                     (Comment *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &comment__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   list_comments_response__init
                     (ListCommentsResponse         *message)
{
  static const ListCommentsResponse init_value = LIST_COMMENTS_RESPONSE__INIT;
  *message = init_value;
}
size_t list_comments_response__get_packed_size
                     (const ListCommentsResponse *message)
{
  assert(message->base.descriptor == &list_comments_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t list_comments_response__pack
                     (const ListCommentsResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &list_comments_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t list_comments_response__pack_to_buffer
                     (const ListCommentsResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &list_comments_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ListCommentsResponse *
       list_comments_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ListCommentsResponse *)
     protobuf_c_message_unpack (&list_comments_response__descriptor,
                                allocator, len, data);
}
void   list_comments_response__free_unpacked
                     (ListCommentsResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &list_comments_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   get_user_details_request__init
                     (GetUserDetailsRequest         *message)
{
  static const GetUserDetailsRequest init_value = GET_USER_DETAILS_REQUEST__INIT;
  *message = init_value;
}
size_t get_user_details_request__get_packed_size
                     (const GetUserDetailsRequest *message)
{
  assert(message->base.descriptor == &get_user_details_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t get_user_details_request__pack
                     (const GetUserDetailsRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &get_user_details_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t get_user_details_request__pack_to_buffer
                     (const GetUserDetailsRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &get_user_details_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GetUserDetailsRequest *
       get_user_details_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GetUserDetailsRequest *)
     protobuf_c_message_unpack (&get_user_details_request__descriptor,
                                allocator, len, data);
}
void   get_user_details_request__free_unpacked
                     (GetUserDetailsRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &get_user_details_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   get_user_details_response__init
                     (GetUserDetailsResponse         *message)
{
  static const GetUserDetailsResponse init_value = GET_USER_DETAILS_RESPONSE__INIT;
  *message = init_value;
}
size_t get_user_details_response__get_packed_size
                     (const GetUserDetailsResponse *message)
{
  assert(message->base.descriptor == &get_user_details_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t get_user_details_response__pack
                     (const GetUserDetailsResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &get_user_details_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t get_user_details_response__pack_to_buffer
                     (const GetUserDetailsResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &get_user_details_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GetUserDetailsResponse *
       get_user_details_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GetUserDetailsResponse *)
     protobuf_c_message_unpack (&get_user_details_response__descriptor,
                                allocator, len, data);
}
void   get_user_details_response__free_unpacked
                     (GetUserDetailsResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &get_user_details_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   add_beer_request__init
                     (AddBeerRequest         *message)
{
  static const AddBeerRequest init_value = ADD_BEER_REQUEST__INIT;
  *message = init_value;
}
size_t add_beer_request__get_packed_size
                     (const AddBeerRequest *message)
{
  assert(message->base.descriptor == &add_beer_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t add_beer_request__pack
                     (const AddBeerRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &add_beer_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t add_beer_request__pack_to_buffer
                     (const AddBeerRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &add_beer_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AddBeerRequest *
       add_beer_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AddBeerRequest *)
     protobuf_c_message_unpack (&add_beer_request__descriptor,
                                allocator, len, data);
}
void   add_beer_request__free_unpacked
                     (AddBeerRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &add_beer_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   add_beer_response__init
                     (AddBeerResponse         *message)
{
  static const AddBeerResponse init_value = ADD_BEER_RESPONSE__INIT;
  *message = init_value;
}
size_t add_beer_response__get_packed_size
                     (const AddBeerResponse *message)
{
  assert(message->base.descriptor == &add_beer_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t add_beer_response__pack
                     (const AddBeerResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &add_beer_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t add_beer_response__pack_to_buffer
                     (const AddBeerResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &add_beer_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AddBeerResponse *
       add_beer_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AddBeerResponse *)
     protobuf_c_message_unpack (&add_beer_response__descriptor,
                                allocator, len, data);
}
void   add_beer_response__free_unpacked
                     (AddBeerResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &add_beer_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   list_beers_request__init
                     (ListBeersRequest         *message)
{
  static const ListBeersRequest init_value = LIST_BEERS_REQUEST__INIT;
  *message = init_value;
}
size_t list_beers_request__get_packed_size
                     (const ListBeersRequest *message)
{
  assert(message->base.descriptor == &list_beers_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t list_beers_request__pack
                     (const ListBeersRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &list_beers_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t list_beers_request__pack_to_buffer
                     (const ListBeersRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &list_beers_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ListBeersRequest *
       list_beers_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ListBeersRequest *)
     protobuf_c_message_unpack (&list_beers_request__descriptor,
                                allocator, len, data);
}
void   list_beers_request__free_unpacked
                     (ListBeersRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &list_beers_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   beer__init
                     (Beer         *message)
{
  static const Beer init_value = BEER__INIT;
  *message = init_value;
}
size_t beer__get_packed_size
                     (const Beer *message)
{
  assert(message->base.descriptor == &beer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t beer__pack
                     (const Beer *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &beer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t beer__pack_to_buffer
                     (const Beer *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &beer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Beer *
       beer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Beer *)
     protobuf_c_message_unpack (&beer__descriptor,
                                allocator, len, data);
}
void   beer__free_unpacked
                     (Beer *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &beer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   list_beers_response__init
                     (ListBeersResponse         *message)
{
  static const ListBeersResponse init_value = LIST_BEERS_RESPONSE__INIT;
  *message = init_value;
}
size_t list_beers_response__get_packed_size
                     (const ListBeersResponse *message)
{
  assert(message->base.descriptor == &list_beers_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t list_beers_response__pack
                     (const ListBeersResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &list_beers_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t list_beers_response__pack_to_buffer
                     (const ListBeersResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &list_beers_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ListBeersResponse *
       list_beers_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ListBeersResponse *)
     protobuf_c_message_unpack (&list_beers_response__descriptor,
                                allocator, len, data);
}
void   list_beers_response__free_unpacked
                     (ListBeersResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &list_beers_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   add_comment_request__init
                     (AddCommentRequest         *message)
{
  static const AddCommentRequest init_value = ADD_COMMENT_REQUEST__INIT;
  *message = init_value;
}
size_t add_comment_request__get_packed_size
                     (const AddCommentRequest *message)
{
  assert(message->base.descriptor == &add_comment_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t add_comment_request__pack
                     (const AddCommentRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &add_comment_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t add_comment_request__pack_to_buffer
                     (const AddCommentRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &add_comment_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AddCommentRequest *
       add_comment_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AddCommentRequest *)
     protobuf_c_message_unpack (&add_comment_request__descriptor,
                                allocator, len, data);
}
void   add_comment_request__free_unpacked
                     (AddCommentRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &add_comment_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   add_comment_response__init
                     (AddCommentResponse         *message)
{
  static const AddCommentResponse init_value = ADD_COMMENT_RESPONSE__INIT;
  *message = init_value;
}
size_t add_comment_response__get_packed_size
                     (const AddCommentResponse *message)
{
  assert(message->base.descriptor == &add_comment_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t add_comment_response__pack
                     (const AddCommentResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &add_comment_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t add_comment_response__pack_to_buffer
                     (const AddCommentResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &add_comment_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AddCommentResponse *
       add_comment_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AddCommentResponse *)
     protobuf_c_message_unpack (&add_comment_response__descriptor,
                                allocator, len, data);
}
void   add_comment_response__free_unpacked
                     (AddCommentResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &add_comment_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   delete_comment_request__init
                     (DeleteCommentRequest         *message)
{
  static const DeleteCommentRequest init_value = DELETE_COMMENT_REQUEST__INIT;
  *message = init_value;
}
size_t delete_comment_request__get_packed_size
                     (const DeleteCommentRequest *message)
{
  assert(message->base.descriptor == &delete_comment_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t delete_comment_request__pack
                     (const DeleteCommentRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &delete_comment_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t delete_comment_request__pack_to_buffer
                     (const DeleteCommentRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &delete_comment_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DeleteCommentRequest *
       delete_comment_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DeleteCommentRequest *)
     protobuf_c_message_unpack (&delete_comment_request__descriptor,
                                allocator, len, data);
}
void   delete_comment_request__free_unpacked
                     (DeleteCommentRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &delete_comment_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   delete_comment_response__init
                     (DeleteCommentResponse         *message)
{
  static const DeleteCommentResponse init_value = DELETE_COMMENT_RESPONSE__INIT;
  *message = init_value;
}
size_t delete_comment_response__get_packed_size
                     (const DeleteCommentResponse *message)
{
  assert(message->base.descriptor == &delete_comment_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t delete_comment_response__pack
                     (const DeleteCommentResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &delete_comment_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t delete_comment_response__pack_to_buffer
                     (const DeleteCommentResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &delete_comment_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DeleteCommentResponse *
       delete_comment_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DeleteCommentResponse *)
     protobuf_c_message_unpack (&delete_comment_response__descriptor,
                                allocator, len, data);
}
void   delete_comment_response__free_unpacked
                     (DeleteCommentResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &delete_comment_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   error__init
                     (Error         *message)
{
  static const Error init_value = ERROR__INIT;
  *message = init_value;
}
size_t error__get_packed_size
                     (const Error *message)
{
  assert(message->base.descriptor == &error__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t error__pack
                     (const Error *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &error__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t error__pack_to_buffer
                     (const Error *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &error__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Error *
       error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Error *)
     protobuf_c_message_unpack (&error__descriptor,
                                allocator, len, data);
}
void   error__free_unpacked
                     (Error *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &error__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor command__field_descriptors[3] =
{
  {
    "commandID",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Command, commandid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "commandType",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Command, commandtype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "commandValue",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Command, commandvalue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned command__field_indices_by_name[] = {
  0,   /* field[0] = commandID */
  1,   /* field[1] = commandType */
  2,   /* field[2] = commandValue */
};
static const ProtobufCIntRange command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor command__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Command",
  "Command",
  "Command",
  "",
  sizeof(Command),
  3,
  command__field_descriptors,
  command__field_indices_by_name,
  1,  command__number_ranges,
  (ProtobufCMessageInit) command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor register_response__field_descriptors[6] =
{
  {
    "nickname",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RegisterResponse, nickname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group_n",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RegisterResponse, group_n),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gamma",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RegisterResponse, gamma),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "q",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RegisterResponse, q),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "a",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RegisterResponse, a),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alpha",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RegisterResponse, alpha),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned register_response__field_indices_by_name[] = {
  4,   /* field[4] = a */
  5,   /* field[5] = alpha */
  2,   /* field[2] = gamma */
  1,   /* field[1] = group_n */
  0,   /* field[0] = nickname */
  3,   /* field[3] = q */
};
static const ProtobufCIntRange register_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor register_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RegisterResponse",
  "RegisterResponse",
  "RegisterResponse",
  "",
  sizeof(RegisterResponse),
  6,
  register_response__field_descriptors,
  register_response__field_indices_by_name,
  1,  register_response__number_ranges,
  (ProtobufCMessageInit) register_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor register_request__field_descriptors[1] =
{
  {
    "nickname",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RegisterRequest, nickname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned register_request__field_indices_by_name[] = {
  0,   /* field[0] = nickname */
};
static const ProtobufCIntRange register_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor register_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RegisterRequest",
  "RegisterRequest",
  "RegisterRequest",
  "",
  sizeof(RegisterRequest),
  1,
  register_request__field_descriptors,
  register_request__field_indices_by_name,
  1,  register_request__number_ranges,
  (ProtobufCMessageInit) register_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor login_challenge_msg1_request__field_descriptors[2] =
{
  {
    "nickname",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LoginChallengeMsg1Request, nickname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sigma",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LoginChallengeMsg1Request, sigma),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned login_challenge_msg1_request__field_indices_by_name[] = {
  0,   /* field[0] = nickname */
  1,   /* field[1] = sigma */
};
static const ProtobufCIntRange login_challenge_msg1_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor login_challenge_msg1_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LoginChallengeMsg1Request",
  "LoginChallengeMsg1Request",
  "LoginChallengeMsg1Request",
  "",
  sizeof(LoginChallengeMsg1Request),
  2,
  login_challenge_msg1_request__field_descriptors,
  login_challenge_msg1_request__field_indices_by_name,
  1,  login_challenge_msg1_request__number_ranges,
  (ProtobufCMessageInit) login_challenge_msg1_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor login_challenge_msg1_response__field_descriptors[1] =
{
  {
    "e",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LoginChallengeMsg1Response, e),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned login_challenge_msg1_response__field_indices_by_name[] = {
  0,   /* field[0] = e */
};
static const ProtobufCIntRange login_challenge_msg1_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor login_challenge_msg1_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LoginChallengeMsg1Response",
  "LoginChallengeMsg1Response",
  "LoginChallengeMsg1Response",
  "",
  sizeof(LoginChallengeMsg1Response),
  1,
  login_challenge_msg1_response__field_descriptors,
  login_challenge_msg1_response__field_indices_by_name,
  1,  login_challenge_msg1_response__number_ranges,
  (ProtobufCMessageInit) login_challenge_msg1_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor login_challenge_msg2_request__field_descriptors[2] =
{
  {
    "s",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LoginChallengeMsg2Request, s),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lambda",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LoginChallengeMsg2Request, lambda),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned login_challenge_msg2_request__field_indices_by_name[] = {
  1,   /* field[1] = lambda */
  0,   /* field[0] = s */
};
static const ProtobufCIntRange login_challenge_msg2_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor login_challenge_msg2_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LoginChallengeMsg2Request",
  "LoginChallengeMsg2Request",
  "LoginChallengeMsg2Request",
  "",
  sizeof(LoginChallengeMsg2Request),
  2,
  login_challenge_msg2_request__field_descriptors,
  login_challenge_msg2_request__field_indices_by_name,
  1,  login_challenge_msg2_request__number_ranges,
  (ProtobufCMessageInit) login_challenge_msg2_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor login_challenge_msg2_response__field_descriptors[1] =
{
  {
    "nickname",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LoginChallengeMsg2Response, nickname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned login_challenge_msg2_response__field_indices_by_name[] = {
  0,   /* field[0] = nickname */
};
static const ProtobufCIntRange login_challenge_msg2_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor login_challenge_msg2_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LoginChallengeMsg2Response",
  "LoginChallengeMsg2Response",
  "LoginChallengeMsg2Response",
  "",
  sizeof(LoginChallengeMsg2Response),
  1,
  login_challenge_msg2_response__field_descriptors,
  login_challenge_msg2_response__field_indices_by_name,
  1,  login_challenge_msg2_response__number_ranges,
  (ProtobufCMessageInit) login_challenge_msg2_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor list_comments_request__field_descriptors[2] =
{
  {
    "beer_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ListCommentsRequest, beer_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "page",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ListCommentsRequest, page),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned list_comments_request__field_indices_by_name[] = {
  0,   /* field[0] = beer_id */
  1,   /* field[1] = page */
};
static const ProtobufCIntRange list_comments_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor list_comments_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ListCommentsRequest",
  "ListCommentsRequest",
  "ListCommentsRequest",
  "",
  sizeof(ListCommentsRequest),
  2,
  list_comments_request__field_descriptors,
  list_comments_request__field_indices_by_name,
  1,  list_comments_request__number_ranges,
  (ProtobufCMessageInit) list_comments_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor comment__field_descriptors[8] =
{
  {
    "comment_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Comment, comment_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "comment_value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Comment, comment_value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "comment_author",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Comment, comment_author),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "beer_id",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Comment, beer_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "s",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Comment, s),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sigma",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Comment, sigma),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lambda",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Comment, lambda),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_private",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Comment, is_private),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned comment__field_indices_by_name[] = {
  3,   /* field[3] = beer_id */
  2,   /* field[2] = comment_author */
  0,   /* field[0] = comment_id */
  1,   /* field[1] = comment_value */
  7,   /* field[7] = is_private */
  6,   /* field[6] = lambda */
  4,   /* field[4] = s */
  5,   /* field[5] = sigma */
};
static const ProtobufCIntRange comment__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor comment__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Comment",
  "Comment",
  "Comment",
  "",
  sizeof(Comment),
  8,
  comment__field_descriptors,
  comment__field_indices_by_name,
  1,  comment__number_ranges,
  (ProtobufCMessageInit) comment__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor list_comments_response__field_descriptors[3] =
{
  {
    "pages_count",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ListCommentsResponse, pages_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_page",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ListCommentsResponse, current_page),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "comments",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ListCommentsResponse, n_comments),
    offsetof(ListCommentsResponse, comments),
    &comment__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned list_comments_response__field_indices_by_name[] = {
  2,   /* field[2] = comments */
  1,   /* field[1] = current_page */
  0,   /* field[0] = pages_count */
};
static const ProtobufCIntRange list_comments_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor list_comments_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ListCommentsResponse",
  "ListCommentsResponse",
  "ListCommentsResponse",
  "",
  sizeof(ListCommentsResponse),
  3,
  list_comments_response__field_descriptors,
  list_comments_response__field_indices_by_name,
  1,  list_comments_response__number_ranges,
  (ProtobufCMessageInit) list_comments_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor get_user_details_request__field_descriptors[2] =
{
  {
    "nickname",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GetUserDetailsRequest, nickname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "page",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GetUserDetailsRequest, page),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned get_user_details_request__field_indices_by_name[] = {
  0,   /* field[0] = nickname */
  1,   /* field[1] = page */
};
static const ProtobufCIntRange get_user_details_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor get_user_details_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GetUserDetailsRequest",
  "GetUserDetailsRequest",
  "GetUserDetailsRequest",
  "",
  sizeof(GetUserDetailsRequest),
  2,
  get_user_details_request__field_descriptors,
  get_user_details_request__field_indices_by_name,
  1,  get_user_details_request__number_ranges,
  (ProtobufCMessageInit) get_user_details_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor get_user_details_response__field_descriptors[8] =
{
  {
    "nickname",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GetUserDetailsResponse, nickname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group_n",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GetUserDetailsResponse, group_n),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gamma",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GetUserDetailsResponse, gamma),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "q",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GetUserDetailsResponse, q),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alpha",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GetUserDetailsResponse, alpha),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pages_count",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GetUserDetailsResponse, pages_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_page",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GetUserDetailsResponse, current_page),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "comments",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GetUserDetailsResponse, n_comments),
    offsetof(GetUserDetailsResponse, comments),
    &comment__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned get_user_details_response__field_indices_by_name[] = {
  4,   /* field[4] = alpha */
  7,   /* field[7] = comments */
  6,   /* field[6] = current_page */
  2,   /* field[2] = gamma */
  1,   /* field[1] = group_n */
  0,   /* field[0] = nickname */
  5,   /* field[5] = pages_count */
  3,   /* field[3] = q */
};
static const ProtobufCIntRange get_user_details_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor get_user_details_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GetUserDetailsResponse",
  "GetUserDetailsResponse",
  "GetUserDetailsResponse",
  "",
  sizeof(GetUserDetailsResponse),
  8,
  get_user_details_response__field_descriptors,
  get_user_details_response__field_indices_by_name,
  1,  get_user_details_response__number_ranges,
  (ProtobufCMessageInit) get_user_details_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor add_beer_request__field_descriptors[1] =
{
  {
    "beer_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AddBeerRequest, beer_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned add_beer_request__field_indices_by_name[] = {
  0,   /* field[0] = beer_name */
};
static const ProtobufCIntRange add_beer_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor add_beer_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AddBeerRequest",
  "AddBeerRequest",
  "AddBeerRequest",
  "",
  sizeof(AddBeerRequest),
  1,
  add_beer_request__field_descriptors,
  add_beer_request__field_indices_by_name,
  1,  add_beer_request__number_ranges,
  (ProtobufCMessageInit) add_beer_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor add_beer_response__field_descriptors[1] =
{
  {
    "beer_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AddBeerResponse, beer_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned add_beer_response__field_indices_by_name[] = {
  0,   /* field[0] = beer_id */
};
static const ProtobufCIntRange add_beer_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor add_beer_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AddBeerResponse",
  "AddBeerResponse",
  "AddBeerResponse",
  "",
  sizeof(AddBeerResponse),
  1,
  add_beer_response__field_descriptors,
  add_beer_response__field_indices_by_name,
  1,  add_beer_response__number_ranges,
  (ProtobufCMessageInit) add_beer_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor list_beers_request__field_descriptors[1] =
{
  {
    "page_number",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ListBeersRequest, page_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned list_beers_request__field_indices_by_name[] = {
  0,   /* field[0] = page_number */
};
static const ProtobufCIntRange list_beers_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor list_beers_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ListBeersRequest",
  "ListBeersRequest",
  "ListBeersRequest",
  "",
  sizeof(ListBeersRequest),
  1,
  list_beers_request__field_descriptors,
  list_beers_request__field_indices_by_name,
  1,  list_beers_request__number_ranges,
  (ProtobufCMessageInit) list_beers_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor beer__field_descriptors[3] =
{
  {
    "beer_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Beer, beer_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "beer_name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Beer, beer_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "beer_creator",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Beer, beer_creator),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned beer__field_indices_by_name[] = {
  2,   /* field[2] = beer_creator */
  0,   /* field[0] = beer_id */
  1,   /* field[1] = beer_name */
};
static const ProtobufCIntRange beer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor beer__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Beer",
  "Beer",
  "Beer",
  "",
  sizeof(Beer),
  3,
  beer__field_descriptors,
  beer__field_indices_by_name,
  1,  beer__number_ranges,
  (ProtobufCMessageInit) beer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor list_beers_response__field_descriptors[3] =
{
  {
    "number_pages",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ListBeersResponse, number_pages),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "page_number",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ListBeersResponse, page_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "beers",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ListBeersResponse, n_beers),
    offsetof(ListBeersResponse, beers),
    &beer__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned list_beers_response__field_indices_by_name[] = {
  2,   /* field[2] = beers */
  0,   /* field[0] = number_pages */
  1,   /* field[1] = page_number */
};
static const ProtobufCIntRange list_beers_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor list_beers_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ListBeersResponse",
  "ListBeersResponse",
  "ListBeersResponse",
  "",
  sizeof(ListBeersResponse),
  3,
  list_beers_response__field_descriptors,
  list_beers_response__field_indices_by_name,
  1,  list_beers_response__number_ranges,
  (ProtobufCMessageInit) list_beers_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor add_comment_request__field_descriptors[4] =
{
  {
    "beer_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AddCommentRequest, beer_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "comment",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AddCommentRequest, comment),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "private_key",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AddCommentRequest, private_key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_private",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(AddCommentRequest, is_private),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned add_comment_request__field_indices_by_name[] = {
  0,   /* field[0] = beer_id */
  1,   /* field[1] = comment */
  3,   /* field[3] = is_private */
  2,   /* field[2] = private_key */
};
static const ProtobufCIntRange add_comment_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor add_comment_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AddCommentRequest",
  "AddCommentRequest",
  "AddCommentRequest",
  "",
  sizeof(AddCommentRequest),
  4,
  add_comment_request__field_descriptors,
  add_comment_request__field_indices_by_name,
  1,  add_comment_request__number_ranges,
  (ProtobufCMessageInit) add_comment_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor add_comment_response__field_descriptors[1] =
{
  {
    "comment_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AddCommentResponse, comment_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned add_comment_response__field_indices_by_name[] = {
  0,   /* field[0] = comment_id */
};
static const ProtobufCIntRange add_comment_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor add_comment_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AddCommentResponse",
  "AddCommentResponse",
  "AddCommentResponse",
  "",
  sizeof(AddCommentResponse),
  1,
  add_comment_response__field_descriptors,
  add_comment_response__field_indices_by_name,
  1,  add_comment_response__number_ranges,
  (ProtobufCMessageInit) add_comment_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor delete_comment_request__field_descriptors[1] =
{
  {
    "comment_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DeleteCommentRequest, comment_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned delete_comment_request__field_indices_by_name[] = {
  0,   /* field[0] = comment_id */
};
static const ProtobufCIntRange delete_comment_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor delete_comment_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DeleteCommentRequest",
  "DeleteCommentRequest",
  "DeleteCommentRequest",
  "",
  sizeof(DeleteCommentRequest),
  1,
  delete_comment_request__field_descriptors,
  delete_comment_request__field_indices_by_name,
  1,  delete_comment_request__number_ranges,
  (ProtobufCMessageInit) delete_comment_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor delete_comment_response__field_descriptors[1] =
{
  {
    "success",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(DeleteCommentResponse, success),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned delete_comment_response__field_indices_by_name[] = {
  0,   /* field[0] = success */
};
static const ProtobufCIntRange delete_comment_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor delete_comment_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DeleteCommentResponse",
  "DeleteCommentResponse",
  "DeleteCommentResponse",
  "",
  sizeof(DeleteCommentResponse),
  1,
  delete_comment_response__field_descriptors,
  delete_comment_response__field_indices_by_name,
  1,  delete_comment_response__number_ranges,
  (ProtobufCMessageInit) delete_comment_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor error__field_descriptors[1] =
{
  {
    "error_message",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Error, error_message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned error__field_indices_by_name[] = {
  0,   /* field[0] = error_message */
};
static const ProtobufCIntRange error__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor error__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Error",
  "Error",
  "Error",
  "",
  sizeof(Error),
  1,
  error__field_descriptors,
  error__field_indices_by_name,
  1,  error__number_ranges,
  (ProtobufCMessageInit) error__init,
  NULL,NULL,NULL    /* reserved[123] */
};
