services:
  nginx:
    image: nginx:alpine
    cpus: 1
    pids_limit: 1024
    mem_limit: 1G
    memswap_limit: 1G
    ulimits:
      nofile:
        soft: 12000
        hard: 12000
    restart: always
    stop_grace_period: 3s
    ports:
      - '8080:8080'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./front:/var/www:ro
    networks:
      - internal
    depends_on:
      - back

  postgres:
    image: postgres:13
    cpus: 2
    pids_limit: 1024
    mem_limit: 1G
    restart: always
    stop_grace_period: 1s
    environment:
      POSTGRES_USER: trusted_trading
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pg_trusted_trading_db
    volumes:
      - ./postgresql/schemas:/docker-entrypoint-initdb.d
      - ./.pgdata:/var/lib/postgresql/data
    networks:
      - internal

  back:
    build: ./back
    cpus: 4
    pids_limit: 2048
    mem_limit: 2G
    ulimits:
      nofile:
        soft: 12000
        hard: 12000
    restart: always
    stop_grace_period: 1s
    volumes:
      - trusted-trading-data:/var/trusted-trading/:rw
    networks:
      - internal
    depends_on:
      - postgres

  cleaner:
    build: ./cleaner
    cpus: 1
    restart: always
    stop_grace_period: 1s
    networks:
      - internal
    depends_on:
      - postgres

volumes:
  trusted-trading-data:

networks:
  internal:
    driver: bridge
